// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvNReBtSu3yyINSo3sTz18t9YvcY-8Aaw',
    appId: '1:921350787967:web:71808bd79bef0dae7b004a',
    messagingSenderId: '921350787967',
    projectId: 'smart1-app',
    authDomain: 'smart1-app.firebaseapp.com',
    storageBucket: 'smart1-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtGVDOPzd_CSyR_SAb7Cp511-wWyTNV8U',
    appId: '1:921350787967:android:0087b914690c47977b004a',
    messagingSenderId: '921350787967',
    projectId: 'smart1-app',
    storageBucket: 'smart1-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUqbXRiIMQePzFGsEu8MMmMoMFiAtVlCY',
    appId: '1:921350787967:ios:71a1d3a95c2ed6157b004a',
    messagingSenderId: '921350787967',
    projectId: 'smart1-app',
    storageBucket: 'smart1-app.appspot.com',
    iosClientId: '921350787967-ft8kn14f0a2iiqgq6mm9jurge5vv4od7.apps.googleusercontent.com',
    iosBundleId: 'com.example.smart1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUqbXRiIMQePzFGsEu8MMmMoMFiAtVlCY',
    appId: '1:921350787967:ios:71a1d3a95c2ed6157b004a',
    messagingSenderId: '921350787967',
    projectId: 'smart1-app',
    storageBucket: 'smart1-app.appspot.com',
    iosClientId: '921350787967-ft8kn14f0a2iiqgq6mm9jurge5vv4od7.apps.googleusercontent.com',
    iosBundleId: 'com.example.smart1',
  );
}
